//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTMC.Utils.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VTMC.Utils.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string ADChk_Done {
            get {
                return ResourceManager.GetString("ADChk_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入长度不正确 的本地化字符串。
        /// </summary>
        internal static string ADChk_InputLen {
            get {
                return ResourceManager.GetString("ADChk_InputLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户关系经理员工号 的本地化字符串。
        /// </summary>
        internal static string ADChk_Item1 {
            get {
                return ResourceManager.GetString("ADChk_Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户关系经理代码 的本地化字符串。
        /// </summary>
        internal static string ADChk_Item2 {
            get {
                return ResourceManager.GetString("ADChk_Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引荐员工号 的本地化字符串。
        /// </summary>
        internal static string ADChk_Item3 {
            get {
                return ResourceManager.GetString("ADChk_Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 授权码 的本地化字符串。
        /// </summary>
        internal static string ADChk_Item4 {
            get {
                return ResourceManager.GetString("ADChk_Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 授权密码 的本地化字符串。
        /// </summary>
        internal static string ADChk_Item5 {
            get {
                return ResourceManager.GetString("ADChk_Item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}只能输入数字 的本地化字符串。
        /// </summary>
        internal static string ADChk_MustNumber {
            get {
                return ResourceManager.GetString("ADChk_MustNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}必须输入 的本地化字符串。
        /// </summary>
        internal static string ADChk_NotEmpty {
            get {
                return ResourceManager.GetString("ADChk_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请联系支行员工填写授权相关信息 的本地化字符串。
        /// </summary>
        internal static string ADChk_Title {
            get {
                return ResourceManager.GetString("ADChk_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 授权码或授权密码错误，请重新输入 的本地化字符串。
        /// </summary>
        internal static string ADChk_ValidatePW {
            get {
                return ResourceManager.GetString("ADChk_ValidatePW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string Button_Confirm {
            get {
                return ResourceManager.GetString("Button_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写日志失败。 的本地化字符串。
        /// </summary>
        internal static string E20206 {
            get {
                return ResourceManager.GetString("E20206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除文件失败 的本地化字符串。
        /// </summary>
        internal static string E20207 {
            get {
                return ResourceManager.GetString("E20207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除PDF文件夹失败 的本地化字符串。
        /// </summary>
        internal static string E20208 {
            get {
                return ResourceManager.GetString("E20208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件上传失败。 的本地化字符串。
        /// </summary>
        internal static string E20210 {
            get {
                return ResourceManager.GetString("E20210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VTM已登录。 的本地化字符串。
        /// </summary>
        internal static string E20308 {
            get {
                return ResourceManager.GetString("E20308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 华为视频当前没有可被释放的呼叫。 的本地化字符串。
        /// </summary>
        internal static string E20318 {
            get {
                return ResourceManager.GetString("E20318", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理超时，请重新再试。 的本地化字符串。
        /// </summary>
        internal static string E20353 {
            get {
                return ResourceManager.GetString("E20353", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置自定义配置信息失败。 的本地化字符串。
        /// </summary>
        internal static string E20370 {
            get {
                return ResourceManager.GetString("E20370", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置视频参数信息失败。 的本地化字符串。
        /// </summary>
        internal static string E20371 {
            get {
                return ResourceManager.GetString("E20371", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断开背甲失败。 的本地化字符串。
        /// </summary>
        internal static string E20507 {
            get {
                return ResourceManager.GetString("E20507", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监控文件夹目录不存在。 的本地化字符串。
        /// </summary>
        internal static string E20703 {
            get {
                return ResourceManager.GetString("E20703", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取Token失败。 的本地化字符串。
        /// </summary>
        internal static string E21203 {
            get {
                return ResourceManager.GetString("E21203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置系统语言失败。 的本地化字符串。
        /// </summary>
        internal static string E21204 {
            get {
                return ResourceManager.GetString("E21204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统错误内存不足等致命问题。 的本地化字符串。
        /// </summary>
        internal static string E21301 {
            get {
                return ResourceManager.GetString("E21301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 华为视频调用过程中发生一般错误。 的本地化字符串。
        /// </summary>
        internal static string E21302 {
            get {
                return ResourceManager.GetString("E21302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 华为视频调用未响应。 的本地化字符串。
        /// </summary>
        internal static string E21303 {
            get {
                return ResourceManager.GetString("E21303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到呼叫对象。 的本地化字符串。
        /// </summary>
        internal static string E21304 {
            get {
                return ResourceManager.GetString("E21304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 华为视频调用参数错误。 的本地化字符串。
        /// </summary>
        internal static string E21309 {
            get {
                return ResourceManager.GetString("E21309", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 华为视频状态错误。 的本地化字符串。
        /// </summary>
        internal static string E21311 {
            get {
                return ResourceManager.GetString("E21311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件不存在。 的本地化字符串。
        /// </summary>
        internal static string E21321 {
            get {
                return ResourceManager.GetString("E21321", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 华为视频呼叫失败错误。 的本地化字符串。
        /// </summary>
        internal static string E21326 {
            get {
                return ResourceManager.GetString("E21326", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 华为视频调用调用超出licesen限制。 的本地化字符串。
        /// </summary>
        internal static string E21340 {
            get {
                return ResourceManager.GetString("E21340", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 华为视频License不足。 的本地化字符串。
        /// </summary>
        internal static string E21351 {
            get {
                return ResourceManager.GetString("E21351", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VTM登录过程中异常发生。 的本地化字符串。
        /// </summary>
        internal static string E21360 {
            get {
                return ResourceManager.GetString("E21360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VTM登出过程中异常发生。 的本地化字符串。
        /// </summary>
        internal static string E21361 {
            get {
                return ResourceManager.GetString("E21361", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 华为视频设置远端窗口失败。 的本地化字符串。
        /// </summary>
        internal static string E21362 {
            get {
                return ResourceManager.GetString("E21362", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 华为视频设置本地窗口失败。 的本地化字符串。
        /// </summary>
        internal static string E21363 {
            get {
                return ResourceManager.GetString("E21363", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 华为视频呼叫失败。 的本地化字符串。
        /// </summary>
        internal static string E21364 {
            get {
                return ResourceManager.GetString("E21364", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 华为视频挂断失败。 的本地化字符串。
        /// </summary>
        internal static string E21365 {
            get {
                return ResourceManager.GetString("E21365", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置视频窗口样式失败。 的本地化字符串。
        /// </summary>
        internal static string E21366 {
            get {
                return ResourceManager.GetString("E21366", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 华为视频发送消息失败。 的本地化字符串。
        /// </summary>
        internal static string E21367 {
            get {
                return ResourceManager.GetString("E21367", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始共享桌面失败。 的本地化字符串。
        /// </summary>
        internal static string E21368 {
            get {
                return ResourceManager.GetString("E21368", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止共享桌面失败。 的本地化字符串。
        /// </summary>
        internal static string E21369 {
            get {
                return ResourceManager.GetString("E21369", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始远程控制失败。 的本地化字符串。
        /// </summary>
        internal static string E21372 {
            get {
                return ResourceManager.GetString("E21372", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止远程控制失败。 的本地化字符串。
        /// </summary>
        internal static string E21373 {
            get {
                return ResourceManager.GetString("E21373", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 华为视频发生未知错误。 的本地化字符串。
        /// </summary>
        internal static string E21399 {
            get {
                return ResourceManager.GetString("E21399", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传入参数错误。 的本地化字符串。
        /// </summary>
        internal static string E21401 {
            get {
                return ResourceManager.GetString("E21401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 摄像头错误。 的本地化字符串。
        /// </summary>
        internal static string E21402 {
            get {
                return ResourceManager.GetString("E21402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联网授权错误。 的本地化字符串。
        /// </summary>
        internal static string E21403 {
            get {
                return ResourceManager.GetString("E21403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其它错误。 的本地化字符串。
        /// </summary>
        internal static string E21404 {
            get {
                return ResourceManager.GetString("E21404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有可用的摄像头。 的本地化字符串。
        /// </summary>
        internal static string E21405 {
            get {
                return ResourceManager.GetString("E21405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联网授权错误。 的本地化字符串。
        /// </summary>
        internal static string E21406 {
            get {
                return ResourceManager.GetString("E21406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其它错误。 的本地化字符串。
        /// </summary>
        internal static string E21407 {
            get {
                return ResourceManager.GetString("E21407", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化人脸识别设备失败。 的本地化字符串。
        /// </summary>
        internal static string E21408 {
            get {
                return ResourceManager.GetString("E21408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取摄像头列表失败。 的本地化字符串。
        /// </summary>
        internal static string E21409 {
            get {
                return ResourceManager.GetString("E21409", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人脸识别开始检测启动失败。 的本地化字符串。
        /// </summary>
        internal static string E21410 {
            get {
                return ResourceManager.GetString("E21410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E219301 : {0} 的本地化字符串。
        /// </summary>
        internal static string E219301 {
            get {
                return ResourceManager.GetString("E219301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取服务器Token失败，请和管理员联系。 的本地化字符串。
        /// </summary>
        internal static string E219302 {
            get {
                return ResourceManager.GetString("E219302", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   查找类似 MVTM以下配置路径不存在。\r配置项:[{0}]\r值:[{1}] 的本地化字符串。
        /// </summary>
        internal static string E219398 {
            get {
                return ResourceManager.GetString("E219398", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统出现异常，请和管理员联系。 的本地化字符串。
        /// </summary>
        internal static string E219399 {
            get {
                return ResourceManager.GetString("E219399", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MVTM发生了未知异常，请和管理员联系。 的本地化字符串。
        /// </summary>
        internal static string E21999 {
            get {
                return ResourceManager.GetString("E21999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 摄像头被占用。 的本地化字符串。
        /// </summary>
        internal static string E22401 {
            get {
                return ResourceManager.GetString("E22401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF签名板初始化失败。 的本地化字符串。
        /// </summary>
        internal static string E22612 {
            get {
                return ResourceManager.GetString("E22612", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF签名板大小变化失败。 的本地化字符串。
        /// </summary>
        internal static string E22613 {
            get {
                return ResourceManager.GetString("E22613", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始监控文件系统失败。 的本地化字符串。
        /// </summary>
        internal static string E22701 {
            get {
                return ResourceManager.GetString("E22701", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止监控文件系统失败。 的本地化字符串。
        /// </summary>
        internal static string E22702 {
            get {
                return ResourceManager.GetString("E22702", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签名板大小变化时出错。 的本地化字符串。
        /// </summary>
        internal static string E22807 {
            get {
                return ResourceManager.GetString("E22807", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签名板初始化失败。 的本地化字符串。
        /// </summary>
        internal static string E22808 {
            get {
                return ResourceManager.GetString("E22808", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭签名板失败 的本地化字符串。
        /// </summary>
        internal static string E22809 {
            get {
                return ResourceManager.GetString("E22809", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍照启动失败。 的本地化字符串。
        /// </summary>
        internal static string E23101 {
            get {
                return ResourceManager.GetString("E23101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有可用的摄像头。 的本地化字符串。
        /// </summary>
        internal static string E23102 {
            get {
                return ResourceManager.GetString("E23102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定摄像头名称不存在。 的本地化字符串。
        /// </summary>
        internal static string E23103 {
            get {
                return ResourceManager.GetString("E23103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍照发生错误。 的本地化字符串。
        /// </summary>
        internal static string E23105 {
            get {
                return ResourceManager.GetString("E23105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件上传失败。 的本地化字符串。
        /// </summary>
        internal static string E23201 {
            get {
                return ResourceManager.GetString("E23201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件下载失败。 的本地化字符串。
        /// </summary>
        internal static string E23202 {
            get {
                return ResourceManager.GetString("E23202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Base64文件上传失败。 的本地化字符串。
        /// </summary>
        internal static string E23205 {
            get {
                return ResourceManager.GetString("E23205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件超大 的本地化字符串。
        /// </summary>
        internal static string E23209 {
            get {
                return ResourceManager.GetString("E23209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 呼叫被拒绝。 的本地化字符串。
        /// </summary>
        internal static string E23305 {
            get {
                return ResourceManager.GetString("E23305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 与服务器失去连接。 的本地化字符串。
        /// </summary>
        internal static string E23306 {
            get {
                return ResourceManager.GetString("E23306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 身份证读卡器打开失败.
        /// </summary>
        internal static string E233101 {
            get {
                return ResourceManager.GetString("E233101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 身份证读卡器关闭失败.
        /// </summary>
        internal static string E233102 {
            get {
                return ResourceManager.GetString("E233102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取身份证读卡器状态失败.
        /// </summary>
        internal static string E233103 {
            get {
                return ResourceManager.GetString("E233103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置身份证读卡器失败.
        /// </summary>
        internal static string E233104 {
            get {
                return ResourceManager.GetString("E233104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 异步扫描身份证失败.
        /// </summary>
        internal static string E233105 {
            get {
                return ResourceManager.GetString("E233105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退卡失败.
        /// </summary>
        internal static string E233106 {
            get {
                return ResourceManager.GetString("E233106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消操作失败.
        /// </summary>
        internal static string E233107 {
            get {
                return ResourceManager.GetString("E233107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卡被夹住需要操作人员干预.
        /// </summary>
        internal static string E233120 {
            get {
                return ResourceManager.GetString("E233120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 由于操作失误或者硬件故障，而未能成功打开或关闭卡口，需要操作人员的干预.
        /// </summary>
        internal static string E233121 {
            get {
                return ResourceManager.GetString("E233121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入的磁道无效导致读取数据失败.
        /// </summary>
        internal static string E233122 {
            get {
                return ResourceManager.GetString("E233122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成之前卡被移除.
        /// </summary>
        internal static string E233123 {
            get {
                return ResourceManager.GetString("E233123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有发现磁道，插卡或者刷卡的方式错误.
        /// </summary>
        internal static string E233124 {
            get {
                return ResourceManager.GetString("E233124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有找到指定的表单.
        /// </summary>
        internal static string E233125 {
            get {
                return ResourceManager.GetString("E233125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安全模式没有成功读取卡的标志.
        /// </summary>
        internal static string E233126 {
            get {
                return ResourceManager.GetString("E233126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插入的卡太短.
        /// </summary>
        internal static string E233127 {
            get {
                return ResourceManager.GetString("E233127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插入的卡太长.
        /// </summary>
        internal static string E233128 {
            get {
                return ResourceManager.GetString("E233128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在退卡时候卡被吞.
        /// </summary>
        internal static string E233129 {
            get {
                return ResourceManager.GetString("E233129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请求被WFSCancelBlockingCall取消.
        /// </summary>
        internal static string E233140 {
            get {
                return ResourceManager.GetString("E233140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 硬件故障.
        /// </summary>
        internal static string E233141 {
            get {
                return ResourceManager.GetString("E233141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内部错误.
        /// </summary>
        internal static string E233142 {
            get {
                return ResourceManager.GetString("E233142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不支持此命令.
        /// </summary>
        internal static string E233143 {
            get {
                return ResourceManager.GetString("E233143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 命令执行超时.
        /// </summary>
        internal static string E233144 {
            get {
                return ResourceManager.GetString("E233144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数是无效的服务句柄.
        /// </summary>
        internal static string E233145 {
            get {
                return ResourceManager.GetString("E233145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP连接丢失.
        /// </summary>
        internal static string E233146 {
            get {
                return ResourceManager.GetString("E233146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 身份证模块处于忙碌状态此时不能运行执行命令.
        /// </summary>
        internal static string E233160 {
            get {
                return ResourceManager.GetString("E233160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 身份证模块发生故障正在重启，请稍后再试.
        /// </summary>
        internal static string E233161 {
            get {
                return ResourceManager.GetString("E233161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人脸识别结束失败。.
        /// </summary>
        internal static string E23401 {
            get {
                return ResourceManager.GetString("E23401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异步获取身份证信息失败。 的本地化字符串。
        /// </summary>
        internal static string E23501 {
            get {
                return ResourceManager.GetString("E23501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取设备状态失败。 的本地化字符串。
        /// </summary>
        internal static string E23502 {
            get {
                return ResourceManager.GetString("E23502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接背甲失败。 的本地化字符串。
        /// </summary>
        internal static string E23503 {
            get {
                return ResourceManager.GetString("E23503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取设备信息失败。 的本地化字符串。
        /// </summary>
        internal static string E23504 {
            get {
                return ResourceManager.GetString("E23504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二代证照片存储路径不存在 的本地化字符串。
        /// </summary>
        internal static string E23505 {
            get {
                return ResourceManager.GetString("E23505", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背甲未开启。 的本地化字符串。
        /// </summary>
        internal static string E23506 {
            get {
                return ResourceManager.GetString("E23506", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF文件下载失败。 的本地化字符串。
        /// </summary>
        internal static string E23601 {
            get {
                return ResourceManager.GetString("E23601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF文件不存在。 的本地化字符串。
        /// </summary>
        internal static string E23602 {
            get {
                return ResourceManager.GetString("E23602", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF文件转图片失败。 的本地化字符串。
        /// </summary>
        internal static string E23603 {
            get {
                return ResourceManager.GetString("E23603", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF文件签名保存失败。 的本地化字符串。
        /// </summary>
        internal static string E23604 {
            get {
                return ResourceManager.GetString("E23604", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户签名信息保存失败。 的本地化字符串。
        /// </summary>
        internal static string E23605 {
            get {
                return ResourceManager.GetString("E23605", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签名板打开失败。 的本地化字符串。
        /// </summary>
        internal static string E23606 {
            get {
                return ResourceManager.GetString("E23606", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF显示缩放变化失败。 的本地化字符串。
        /// </summary>
        internal static string E23607 {
            get {
                return ResourceManager.GetString("E23607", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF显示内容切换失败。 的本地化字符串。
        /// </summary>
        internal static string E23608 {
            get {
                return ResourceManager.GetString("E23608", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户签名失败。 的本地化字符串。
        /// </summary>
        internal static string E23609 {
            get {
                return ResourceManager.GetString("E23609", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户签名提交失败。 的本地化字符串。
        /// </summary>
        internal static string E23610 {
            get {
                return ResourceManager.GetString("E23610", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF滑动失败。 的本地化字符串。
        /// </summary>
        internal static string E23611 {
            get {
                return ResourceManager.GetString("E23611", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF签名板Cancel处理失败。 的本地化字符串。
        /// </summary>
        internal static string E23614 {
            get {
                return ResourceManager.GetString("E23614", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF签名板Clear处理失败。 的本地化字符串。
        /// </summary>
        internal static string E23615 {
            get {
                return ResourceManager.GetString("E23615", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF签名板Confirm处理失败。 的本地化字符串。
        /// </summary>
        internal static string E23616 {
            get {
                return ResourceManager.GetString("E23616", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF签名处理失败。 的本地化字符串。
        /// </summary>
        internal static string E23617 {
            get {
                return ResourceManager.GetString("E23617", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示PDF超时消息窗口失败。 的本地化字符串。
        /// </summary>
        internal static string E23619 {
            get {
                return ResourceManager.GetString("E23619", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭PDF超时消息窗口失败。 的本地化字符串。
        /// </summary>
        internal static string E23620 {
            get {
                return ResourceManager.GetString("E23620", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF业务终止失败。 的本地化字符串。
        /// </summary>
        internal static string E23699 {
            get {
                return ResourceManager.GetString("E23699", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开签名板失败。 的本地化字符串。
        /// </summary>
        internal static string E23802 {
            get {
                return ResourceManager.GetString("E23802", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签名中出现错误。 的本地化字符串。
        /// </summary>
        internal static string E23803 {
            get {
                return ResourceManager.GetString("E23803", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签名板Clear处理失败。 的本地化字符串。
        /// </summary>
        internal static string E23804 {
            get {
                return ResourceManager.GetString("E23804", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签名板Cancel处理失败。 的本地化字符串。
        /// </summary>
        internal static string E23805 {
            get {
                return ResourceManager.GetString("E23805", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存签名信息失败。 的本地化字符串。
        /// </summary>
        internal static string E23806 {
            get {
                return ResourceManager.GetString("E23806", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E239201：{0} 的本地化字符串。
        /// </summary>
        internal static string E239201 {
            get {
                return ResourceManager.GetString("E239201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MVTM已经运行，不能再次打开。 的本地化字符串。
        /// </summary>
        internal static string E239202 {
            get {
                return ResourceManager.GetString("E239202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签名授权失败。 的本地化字符串。
        /// </summary>
        internal static string E239501 {
            get {
                return ResourceManager.GetString("E239501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭摄像头失败。 的本地化字符串。
        /// </summary>
        internal static string E24104 {
            get {
                return ResourceManager.GetString("E24104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF处理异常。 的本地化字符串。
        /// </summary>
        internal static string E24618 {
            get {
                return ResourceManager.GetString("E24618", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭签名窗口失败。 的本地化字符串。
        /// </summary>
        internal static string E24801 {
            get {
                return ResourceManager.GetString("E24801", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E249101：{0} 的本地化字符串。
        /// </summary>
        internal static string E249101 {
            get {
                return ResourceManager.GetString("E249101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E249102：{0}成功。 的本地化字符串。
        /// </summary>
        internal static string E249102 {
            get {
                return ResourceManager.GetString("E249102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E249103：{0}失败。 的本地化字符串。
        /// </summary>
        internal static string E249103 {
            get {
                return ResourceManager.GetString("E249103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E249401：{0} 的本地化字符串。
        /// </summary>
        internal static string E249401 {
            get {
                return ResourceManager.GetString("E249401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zh 的本地化字符串。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回首页 的本地化字符串。
        /// </summary>
        internal static string M_Button_BackHome {
            get {
                return ResourceManager.GetString("M_Button_BackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string M_Button_Cancel {
            get {
                return ResourceManager.GetString("M_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string M_Button_CancelOK {
            get {
                return ResourceManager.GetString("M_Button_CancelOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继续 的本地化字符串。
        /// </summary>
        internal static string M_Button_Continue {
            get {
                return ResourceManager.GetString("M_Button_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string M_Button_No {
            get {
                return ResourceManager.GetString("M_Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string M_Button_OK {
            get {
                return ResourceManager.GetString("M_Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重试 的本地化字符串。
        /// </summary>
        internal static string M_Button_Retry {
            get {
                return ResourceManager.GetString("M_Button_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string M_Button_Yes {
            get {
                return ResourceManager.GetString("M_Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注意 的本地化字符串。
        /// </summary>
        internal static string M_Caption_Attention {
            get {
                return ResourceManager.GetString("M_Caption_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string M_Caption_Error {
            get {
                return ResourceManager.GetString("M_Caption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        internal static string M_Caption_Info {
            get {
                return ResourceManager.GetString("M_Caption_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提问 的本地化字符串。
        /// </summary>
        internal static string M_Caption_Question {
            get {
                return ResourceManager.GetString("M_Caption_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作超时 的本地化字符串。
        /// </summary>
        internal static string M_Label_Timeout {
            get {
                return ResourceManager.GetString("M_Label_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string PDF_Button_Confirm {
            get {
                return ResourceManager.GetString("PDF_Button_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请继续阅读 的本地化字符串。
        /// </summary>
        internal static string PDF_Read {
            get {
                return ResourceManager.GetString("PDF_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请使用签名笔 的本地化字符串。
        /// </summary>
        internal static string PDF_Sign {
            get {
                return ResourceManager.GetString("PDF_Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Sign_Cancel {
            get {
                return ResourceManager.GetString("Sign_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        internal static string Sign_Clear {
            get {
                return ResourceManager.GetString("Sign_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        internal static string Sign_Done {
            get {
                return ResourceManager.GetString("Sign_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请签名 的本地化字符串。
        /// </summary>
        internal static string Sign_Title {
            get {
                return ResourceManager.GetString("Sign_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 摄像头被占用 的本地化字符串。
        /// </summary>
        internal static string E23106 {
            get {
                return ResourceManager.GetString("W20101", resourceCulture);
            }
        }
    }
}
